name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
  AWS_S3_BUCKET: terraform-s3asel
  AWS_REGION: us-east-2

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Format Terraform 
      run: terraform fmt -check

    - name: Initialize Terraform
      run: terraform init -backend-config="bucket=terraform-s3asel"

    # - name: Plan Terraform
    #   run: terraform plan

    # - name: Apply Terraform
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only apply on main branch push
    #   run: terraform apply -auto-approve

    # You may want to include more steps such as testing, linting, etc. before applying Terraform changes.
